# Test Requests for TMM Application Web Application
# database applications created if not exists when server is started

### Get Data from Table 'applications'
GET http://localhost:3003/applications

### Delete Application with specified id after last slash
DELETE http://localhost:3003/delete/application/11

### Post Data to Table 'applications'
POST http://localhost:3003/apply
Content-Type: application/json

{
    "name": "Max",
    "birthdate": "1999-01-01",
    "phonenumber": "+49 157 12345678", 
    "address": "Musterstraße 23, 09648 Mittweida, Germany", 
    "abbr": "mmusters", 
    "course": "Applied Computer Science", 
    "seminargroup": "IF21wS1-B", 
    "position": "Driving Dynamics"
}

### Delete all Data from Table 'applications'
DELETE http://localhost:3003/delete

// add the following function to server.js to make use of test request
// test route to delete everything from the 'applications' table
// app.delete('/delete', async (req, res) => {
    //try {
        //await client.query('DELETE FROM applications')
        //res.status(200).send('Successfully deleted everything from table!');
    //} catch (err) {
        //console.error(err)
        //res.status(500).send('Internal Server Error');
    //}
//})

###