name: Cypress Test (Application Form)

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Start backend server
        working-directory: server
        run: docker-compose up --build

      - name: Run Cypress tests
        run: npm run cypress:run:component