name: Cypress Test (Application Form)

on:
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      PORT: ${{ secrets.PORT }}
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - ${{ secrets.DB_PORT }}:5432
      app:
        build: .
        ports:
          - ${{ secrets.PORT }}:${{ secrets.PORT }}
        env:
          DB_HOST: db
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          PORT: ${{ secrets.PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          component: true

      
