name: Cypress Test (Application Form)

on:
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          component: true
